### ISSUE TITLE
Bluey HID code sample code

### ISSUE THREAD

**Issue by iayanpahwa** [electronut/ElectronutLabs-bluey#10]
Is it possible to use Bluey for Bluetooth based HID applications? I'd really appreciate if you could share a sample code or pointers? Would be happy to experiment with it and share my thoughts.

**Comment by mkvenkit** [comment]
Check out the HID mouse and keyboard examples provided by Nordic. (I haven't tried them myself.)

http://infocenter.nordicsemi.com/topic/com.nordic.infocenter.sdk5.v15.0.0/ble_sdk_app_hids_keyboard.html?cp=4_0_0_4_1_2_15
