### ISSUE TITLE
Migrate readme from tavish

### ISSUE THREAD

**Issue by electronut** [electronut/ElectronutLabs-bluey#5]
In:

https://github.com/electronut/ElectronutLabs-bluey/blob/master/arduino_setup.md

> Please follow instructions from ntavish/arduino-bluey.

Please migrate Arduino setup instructions to this repo.

**Comment by ntavish** [comment]
Done in aff688514564c49395b122e441d8fc77314938cf, please check and close.

**Comment by electronut** [comment]
Thanks
