### ISSUE TITLE
No support for Black Magic Probe to program the examples to Bluey

### ISSUE THREAD

**Issue by EarthLord** [electronut/ElectronutLabs-bluey#6]
Since Electronut is providing Bumpy, can Black Magic Probe (BMP) be supported for programming/debugging the Bluey with the examples provided? 

For now I'm copying the examples provided along with `bluey-common` to the `examples\ble_peripheral` folder of nRF5 SDK 12.2.0. The compilation is successful in the `/bluey1.2/s132/armgcc/` folder. Next I merge the s132 hex file and the compiled hex file with in the armgcc folder.

` srec_cat ../../../../../../components/softdevice/s132/hex/s132_nrf52_3.0.0_softdevice.hex -Intel _build/nrf52832_xxaa.hex -Intel -O _build/full.hex -Intel --line-length=44`

The programming of the merged hex file is done with BMP by the command 

`sudo arm-none-eabi-gdb -q -ex 'target extended-remote /dev/ttyBmpGdb' -ex 'monitor swdp_scan' -ex 'attach 1' -ex 'load' -ex 'compare-sections' -ex 'detach' -ex 'quit' _build/full.hex`

This flashed the merged hex file but Bluey doesn't seem to work as intended. Post erasing all using this command also didn't work https://github.com/Appiko/nrf5x-firmware/blob/master/application/Makefile.common#L277

If there is an official way, I can follow that. 
Thanks.

**Comment by rishi-electronut** [comment]
**bluey-sensor-test-BLE** example was selected for bumpy test. The generated hex file was merged with softdevice to create a packaged application. Packaged application can be found towards the end of this post.
 
This application was transferred to bluey (completely erased chip). On execution, bluey advertised as  **Bluey-BLE** successfully. 

Following steps will walk you through the procedure employed to conduct above mentioned test.

* Issue `make` command to generate hex file.

* Using softdevice - s132 and above generated hex file, a package is generated using **mergehex** tool. It can be obtained by downloading **nrfutils** package or by installing nRFgo Studio.

* Issue following command to generate **softdevice+application** package as a hex file.

`mergehex -m s132-softdevice.hex bluey-ble.hex -o bluey-ble-pkg.hex`

* Connect bluey to bumpy and bumpy to PC. Find out the relevant COM ports.

* Run ARM-debugger by issuing `arm-none-eabi-gdb` command.

* Issue following commands: 

`target extended-remote \\.\COM60`     ............................... (`\\.\` - issue in Windows for COM ports over 10)

`monitor swdp_scan`

`attach 1`

`load bluey-ble-pkg.hex`

`run`

* Press **Ctrl + C** to generate keyboard interrupt and halt debugging.

* Issue `detach` command to remove target.

[bluey-ble-pkg.zip](https://github.com/electronut/ElectronutLabs-bluey/files/1169298/bluey-ble-pkg.zip)

**Comment by EarthLord** [comment]
This is essentially what I did, but with a different tool to merge the hex files. I tried using your merged hex from the zip that you've attached with a BMP, but that still isn't providing any advertisements on scanning.

Can the Makefile for the examples in a Linux environment be updated to use either JLink or BMP?

**Comment by electronut** [comment]
I downloaded the merged hex file and tried the same on OS X - works fine. So looks like either you are unable to erase your board somehow, or there is a hardware issue. It could be that the code is just crashing because a sensor is not responding via I2C...

**Comment by electronut** [comment]
@EarthLord - is the sensor_test (non BLE) working?

**Comment by rishi-electronut** [comment]
The above test was performed with a new board.
Also, the package was uploaded to a bluey with blank chip directly using nRFgo Studio. 

Bluey advertising successfully in both cases.

**Comment by EarthLord** [comment]
I'll check with another board later in the evening and let you now. If I figure out what's happening, I could send a pull request to add support to BMP in this repo in a Linux based environment.

**Comment by electronut** [comment]
Sure, thanks. We can replace the board if that's the issue.

*Mahesh Venkitachalam*
Founder, Electronut Labs
electronut.in

**Comment by EarthLord** [comment]
Ok, if I comment out all the TWI related activities in the bluey-beacon example I can get it to work. Seems like an issue with one of the sensors on this board.
I'll work on adding the Bluey support to this repo. I'll add a default debugger in the Makefile and a user can change it when using the make command. Would this be fine?

**Comment by electronut** [comment]
Yes, sounds fine. Please drop the board at our office and we'll give you a
new one.

That HDC1010 BGA chip is a pain. We're changing it in the next version...

*Mahesh Venkitachalam*
Founder, Electronut Labs
electronut.in

**Comment by electronut** [comment]
I'll close this - you can open a new one for any other issues.

**Comment by electronut** [comment]
@EarthLord is your board version 1.1?

**Comment by EarthLord** [comment]
Bluey 1.0.
I just created a PR for adding BMP support too. Please check for the beacon example and if its fine, it can be replicated for the other examples too.
