### ISSUE TITLE
Create a VirtualBox image for Bluey dev

### ISSUE THREAD

**Issue by electronut** [electronut/ElectronutLabs-bluey#8]
Which contains all the tools needed to program bluey...

**Comment by AdySan** [comment]
Isn't a docker image possible too?

**Comment by electronut** [comment]
Sorry, I don't like docker. I think it creates more problems than it solves...

**Comment by AdySan** [comment]
I see, interesting. I'm rather new to docker too, but it's been a great help running a bunch of containers on the home server. It even runs rather complicated things like a IKEv2/IPSec VPN server seamlessly. A nRF toolchain would be a great use case.

**Comment by electronut** [comment]
Hmmm...I see no need for it. A Linux VM is far more useful, I think, since
you have a chance to install a bunch of other useful tools as well. The
last time I used docker for a web forum, it was a complete disaster when we
changed the hosting. At my age, I tend to mistrust anything that has too
many layers and dependencies. :-)
